### ISSUE TITLE
old metrics do not disappear and will be reported forever

### ISSUE THREAD

**Issue by codingkrabbe** [davidgiga1993/pollect#20]
When reporting on metrics, metrics that were once in the exporter and are not anymore will still be reported with their old value forever.
This does not make sense, they should be dropped instead.

**Comment by davidgiga1993** [comment]
Reopen since the change had to be reverted because of unforeseen consequences

**Comment by codingkrabbe** [comment]
:O
Higher securiry?:-)

David ***@***.***> schrieb am Fr., 5. Aug. 2022, 14:57:
